import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#F9F9F9',
    alignItems: 'center',
    paddingTop: 80,
  },
  logo: {
    fontWeight: 'bold',
    fontSize: 25,
    color: '#00AAAB',
    marginBottom: 30,
  },
  inputView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '90%',
    height: 50,
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  inputIcon: {
    paddingRight: 10,
  },
  inputText: {
    width: '100%',
    height: 50,
  },
  forgot: {
    color: 'white',
    fontSize: 11,
  },
  loginBtnEnabled: {
    width: '95%',
    backgroundColor: '#00AAAB',
    borderRadius: 25,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  loginBtnDisabled: {
    width: '95%',
    backgroundColor: '#3CDECE',
    borderRadius: 25,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  loginButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  textForgotSignup: {
    color: '#00AAAB',
    fontWeight: 'bold',
    fontSize: 14,
  },
  backBtnEnabled: {
    width: '80%',
    backgroundColor: '#fb5b5a',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  sendText: {
    color: 'white',
    fontSize: 11,
  },
  errorView: {
    alignSelf: 'flex-start',
    paddingLeft: 50,
  },
  errorMessage: {
    color: 'white',
    fontSize: 11,
  },
  createBtnEnabled: {
    width: '80%',
    backgroundColor: '#fb5b5a',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  createBtnDisabled: {
    width: '80%',
    backgroundColor: '#d4807f',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  createText: {
    color: 'white',
    fontSize: 11,
  },
  imageLogo: {
    width: 180,
    height: 180,
  },
});
